import { Manufacturer, SolarProduct } from '@/types/catalogue';

export const INITIAL_MANUFACTURERS: Manufacturer[] = [
  { id: 'adani', name: 'Adani Solar', isActive: true },
  { id: 'tatapower', name: 'Tata Power Solar', isActive: true },
  { id: 'waaree', name: 'Waaree Energies', isActive: true },
  { id: 'vikram', name: 'Vikram Solar', isActive: true },
  { id: 'goldi', name: 'Goldi Solar', isActive: true },
  { id: 'growatt', name: 'Growatt', isActive: true },
  { id: 'sungrow', name: 'Sungrow', isActive: true },
  { id: 'deye', name: 'Deye', isActive: true },
  { id: 'polycab', name: 'Polycab', isActive: true },
  { id: 'havells', name: 'Havells', isActive: true },
  { id: 'schneider', name: 'Schneider Electric', isActive: true },
  { id: 'exide', name: 'Exide Industries', isActive: true },
];

export const INITIAL_PRODUCTS: SolarProduct[] = [
  {
    id: 'prod-1',
    category: 'Solar Panels',
    brand: 'Adani Solar',
    model: 'Elan Shine Bifacial Mono PERC',
    capacity: '545W - 550W',
    specs: { 'Cell Type': 'Bifacial Mono PERC', 'Efficiency': '21.3%', 'Module Dimension': '2279 x 1134 mm' },
    features: ['Up to 25% bifacial gain', 'PID Resistant', 'IP68 Junction Box'],
    warranty: '12 Years Product, 30 Years Linear Performance',
    certifications: ['ALMM Approved', 'BIS Certified', 'IEC 61215'],
    isActive: true,
  },
  {
    id: 'prod-2',
    category: 'Inverters',
    brand: 'Growatt',
    model: 'MID 15-25KTL3-X',
    capacity: '20 kW Three Phase',
    specs: { 'Max Efficiency': '98.7%', 'MPPT Trackers': '2', 'AC Nominal Output': '400V 3-Phase' },
    features: ['Touch key and OLED display', 'Type II SPD on DC & AC', 'Export limitation support'],
    warranty: '5 Years Standard (Extendable to 10 Years)',
    certifications: ['IEC 62109', 'VDE-AR-N 4105'],
    isActive: true,
  },
  {
    id: 'prod-3',
    category: 'Batteries',
    brand: 'Exide Industries',
    model: 'Solar Tubemaster C10',
    capacity: '150Ah / 12V',
    specs: { 'Technology': 'Tall Tubular Lead-Acid', 'Cycle Life': '1500 cycles @ 80% DOD' },
    features: ['Low antimony alloy', 'Spill proof vent plugs', 'High temperature tolerance'],
    warranty: '5 Years Pro-rata Warranty',
    certifications: ['IS 13369'],
    isActive: true,
  },
  {
    id: 'prod-4',
    category: 'Cables',
    brand: 'Polycab',
    model: 'Solar DC XLPO 4 sq.mm',
    capacity: '1500V DC Rated',
    specs: { 'Conductor': 'Tinned Copper Class 5', 'Insulation': 'Cross-linked Polyolefin (XLPO)' },
    features: ['UV & Ozone Resistant', 'Flame Retardant', 'Halogen Free'],
    warranty: '25 Years Rated Life',
    certifications: ['EN 50618 (TUV)', 'IS 694'],
    isActive: true,
  },
];
